

start = 2005-01-01

[high_school]
date = 2019-02-01
title = "started school"
location = "Mount Albert Grammar School"
finished = 2023-08-20
row = 0


[primary_school]
date = 2010-08-28
title = "started school"
location = "balmoral school"
finished = 2018-12-20
row = 0

[born]
date = 2005-08-28
title = "born"
location = "auckland"